### PR TITLE
Add Letterboxd support

### PR DESCRIPTION
**Pull request by zanetaylor**
Addresses #52

### CODE REVIEW

**Comment by piejanssens** [comment]
Please check https://github.com/roboticsound/Pulsarr/blob/master/popup.js
and #51 as an example.
More is needed to add support for another site.

**Comment by gabri94** [comment]
I'd like to contribute and close this PR.
What should i do?

**Comment by zanetaylor** [comment]
Sorry, I missed the update to this! Can you be more specific about what else is required for this PR, @piejanssens ?

**Comment by piejanssens** [comment]
I think the author has abandoned this project. Might be better to move to a more active fork: https://github.com/zebbe152/Pulsarr

**Comment by zanetaylor** [comment]
Done: https://github.com/zebbe152/Pulsarr/pull/3

**Pull request closed without merging**
